name: film
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dio: ^4.0.6
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  animate_do: ^2.1.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  shimmer: ^2.0.0
  google_fonts: ^4.0.3
  youtube_player_flutter: ^8.1.1
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
flutter_icons:
  android: true
  image_path: "assets/images/icon/movie.png"    
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icon_bottom_navigation/
